// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM_VIII_TESTE.Data;

namespace PIM_VIII_TESTE.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221105135537_Criacao-Inicial2")]
    partial class CriacaoInicial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PIM_VIII_TESTE.Models.Pessoas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .HasColumnName("Cpf")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<long>("Telefone")
                        .HasColumnName("telefone")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PessoasTeste");
                });
#pragma warning restore 612, 618
        }
    }
}
